name: Build
on: 
  push:
    branches:
     - 'master'
    # tags:
    #   - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm build
      - name: Upload Distibution Directory
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
    
