name: Build
on: 
  push:
    branches:
     - 'master'
    # tags:
    #   - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: pwd 
      - run: ls
      - name: Upload Distibution Directory
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
    
