name: Build
on: 
  push:
    branches:
      - 'master'
    # tags:
    #   - '*'
jobs:
  build:
    name: Build
    run-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm build
    
