name: Build
on: 
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - name: Upload Distibution Directory
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set Node Package Version
        run: npm version --git-tag-version false ${{ steps.get_version.outputs.VERSION }}
      - name: Publish Node Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

  
